# Generated by Django 2.2.6 on 2019-10-22 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_account_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='mobile',
            field=models.CharField(default='EMPTY STRING', max_length=12),
        ),
    ]
