# Generated by Django 2.2.6 on 2019-10-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_account_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='KycInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('mobile', models.CharField(max_length=17)),
                ('idprooffront', models.ImageField(upload_to='pictures/proof/')),
                ('idproofback', models.ImageField(upload_to='pictures/proof/')),
            ],
        ),
    ]
