# Generated by Django 2.2.6 on 2019-10-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20191029_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycinfo',
            name='idproofback',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='kycinfo',
            name='idprooffront',
            field=models.BinaryField(),
        ),
    ]
