# Generated by Django 2.2.6 on 2019-10-29 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20191029_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycinfo',
            name='idproofback',
        ),
        migrations.RemoveField(
            model_name='kycinfo',
            name='idprooffront',
        ),
    ]
