# Generated by Django 2.2.6 on 2019-10-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20191029_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycinfo',
            name='idproof',
            field=models.FileField(default=2, upload_to='pictures/'),
            preserve_default=False,
        ),
    ]
