# Generated by Django 2.2.6 on 2019-10-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_kycinfo_idproof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kycinfo',
            old_name='idproof',
            new_name='idprooffront',
        ),
        migrations.AddField(
            model_name='kycinfo',
            name='idproofback',
            field=models.ImageField(default=2, upload_to='pictures/'),
            preserve_default=False,
        ),
    ]
