# Generated by Django 2.2.6 on 2019-10-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20191029_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycinfo',
            name='idproofback',
            field=models.FileField(upload_to='pictures/'),
        ),
    ]
