# Generated by Django 2.2.6 on 2019-10-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20191029_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycinfo',
            name='idproofback',
            field=models.ImageField(upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='kycinfo',
            name='idprooffront',
            field=models.ImageField(upload_to='pictures/'),
        ),
    ]
