# Generated by Django 2.2.6 on 2019-10-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20191029_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycinfo',
            name='kycstatus',
            field=models.IntegerField(blank=True, default=2),
            preserve_default=False,
        ),
    ]
