# Generated by Django 2.2.6 on 2019-10-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_kycinfo_kycstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycinfo',
            name='kycstatus',
            field=models.IntegerField(null=True),
        ),
    ]
