# Generated by Django 2.2.6 on 2019-10-29 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20191029_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycinfo',
            name='userid',
            field=models.IntegerField(default=None),
        ),
    ]
