# Generated by Django 2.2.6 on 2019-10-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_kycinfo_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycinfo',
            name='userid',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
