# Generated by Django 2.2.6 on 2019-10-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_remove_kycinfo_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycinfo',
            name='token',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
