# Generated by Django 2.2.6 on 2019-10-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_project_projectinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='maxprice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='minprice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='projectcode',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectinfo',
            name='projectname',
            field=models.CharField(max_length=100),
        ),
    ]
