# Generated by Django 2.2.6 on 2019-10-30 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20191030_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinfo',
            name='projectcode',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
