# Generated by Django 2.2.6 on 2019-10-30 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20191030_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinfo',
            name='userid',
        ),
    ]
