# Generated by Django 2.2.6 on 2019-10-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_remove_projectinfo_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='mobile',
            field=models.CharField(max_length=30),
        ),
    ]
