# Generated by Django 2.2.6 on 2019-10-31 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_auto_20191030_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=50)),
                ('categorycode', models.CharField(max_length=60)),
                ('subcategoryname', models.CharField(max_length=60)),
                ('subcategorycode', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.RemoveField(
            model_name='account',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='kycinfo',
            name='token',
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='categorycode',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='subcategorycode',
            field=models.CharField(default=None, max_length=60),
        ),
    ]
