# Generated by Django 2.2.6 on 2019-10-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_auto_20191031_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycinfo',
            name='username',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
