# Generated by Django 2.2.6 on 2019-11-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_kycinfo_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='postproject',
            name='projectcode',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
