# Generated by Django 2.2.6 on 2019-11-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_postproject_projectcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postproject',
            name='projectcode',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
