# Generated by Django 2.2.6 on 2019-11-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_auto_20191101_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='categorycode',
            field=models.CharField(default=None, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='subcategorycode',
            field=models.CharField(default=None, max_length=60, null=True),
        ),
    ]
