# Generated by Django 2.2.6 on 2019-11-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_auto_20191105_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
